[EASI-3965] New financial guarantee question for ISP
CMSgov/mint-app pull request #1006
Opened 2024-03-13 20:55 UTC by StevenWadeOddball

# EASI-3965, EASI-3964

## Changes and Description

- Added new questions on the backend
- Front end is a work in progress.

## How to test this change

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2024-03-18 08:36 UTC, OddTomBrooks commented
As discussed on Friday, as this is part of a full-stack pass in progress I am approving the backend work via this comment. I have no suggestions for the code itself, the unit tests pass, and the postman query functions as expected.

2024-03-20 13:57 UTC, StevenWadeOddball commented
Converting to Draft til the FE is implemented

2024-03-27 17:02 UTC, garyjzhao commented on src/components/AddNote/__snapshots__/index.test.tsx.snap
> +    class="margin-top-3 margin-bottom-6"
![image](https://github.com/CMSgov/mint-app/assets/2349702/cf32a0c3-470d-475c-8d97-646325cce8ff)

2024-03-27 17:02 UTC, garyjzhao commented on src/components/AddNote/index.tsx
> +    <div className={classNames('margin-top-3 margin-bottom-6', className)}>
![image](https://github.com/CMSgov/mint-app/assets/2349702/1da11f67-13bd-4150-936d-92dddf774cd5)

2024-03-27 17:07 UTC, garyjzhao commented on src/components/AddNote/index.tsx
> +    <div className={classNames('margin-top-3 margin-bottom-6', className)}>
This change to match resulted to a bunch of snapshot updates. Just ICYWW

2024-04-01 16:20 UTC, patrickseguraoddball requested changes
The readonly render does not match Figma.  In Figma, UX has combined both questions into one, absolving the need for a `parentRelation`/`childRelation` field.  Instead the `readonly` label should be used to represent both questions

https://www.figma.com/file/6tkIhfNfcsKEAkqXo1qvXH/MINT---Read-Only-View?type=design&node-id=4247-64648&mode=design&t=YHREGFRhAmn29gvJ-0

The parent/child relations controls these alerts that allow you to toggle hidden questions.  This alert should not be shown as both questions are combined in readonly
![Screenshot 2024-04-01 at 11 20 35 AM](https://github.com/CMSgov/mint-app/assets/95709965/9d60ef73-8140-478c-9168-44ca29b72b3d)

2024-04-02 22:06 UTC, patrickseguraoddball requested changes
These new fields need to be included in the csv export

2024-04-03 20:26 UTC, patrickseguraoddball approved these changes
LG!

2024-04-04 15:20 UTC, merged