[EASI-4240, EASI-4239] Operational Solutions tabel updates
CMSgov/mint-app pull request #1068
Opened 2024-04-23 16:12 UTC by garyjzhao

# EASI-4240, EASI-4239

## Changes and Description

- Moved `solutions` column to far left
- Changed `must finish by` to `must be ready by`

## How to test this change

1. Navigate to operaitonal needs and solution page and verify changes

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2024-04-23 20:51 UTC, patrickseguraoddball commented on src/views/ModelPlan/TaskList/ITSolutions/Home/operationalNeedsTable.tsx
> +                      // width: index === 5 ? '235px' : 'auto'
Can probably remove this commented out code

2024-04-24 14:23 UTC, patrickseguraoddball requested changes
This table column became squished.  Should be a small fix

![Screenshot 2024-04-24 at 9 22 21 AM](https://github.com/CMSgov/mint-app/assets/95709965/05988a3d-86b4-44df-ab5e-2b296729f9b2)

2024-04-24 18:23 UTC, garyjzhao commented on src/views/ModelPlan/TaskList/ITSolutions/Home/operationalNeedsTable.tsx
> +                        (index === 3 && type !== 'possibleNeeds' && '100px') ||
![image](https://github.com/CMSgov/mint-app/assets/2349702/beb92132-199c-4c14-aab7-19d3fb5bb406)

2024-04-24 20:17 UTC, patrickseguraoddball approved these changes
LG

2024-04-24 20:17 UTC, merged