[EASI-4473] Notification: Data Exchange Approach Completed
CMSgov/mint-app pull request #1209
Opened 2024-07-02 20:57 UTC by OddTomBrooks

# EASI-4473

## Description

- SQL Store methods
- GQL
- Added activity type
- Unit test (activity)
- Unit test (email)
- Seeding test / email dispatch
- Router helper function for integration with data exchange implementation

## How to test this change

- Validate unit tests by running `scripts/dev test:go`
- Validate footers for email recipients and no footers for MINT Team email
- Use Get Notification endpoint on Postman to validate Notification data

## PR Author Checklist

- [x] I have provided a detailed description of the changes in this PR.
- [x] I have provided clear instructions on how to test the changes in this PR.
- [x] I have updated tests or written new tests as appropriate in this PR.
- [x] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines

- It's best to pull the branch locally and test it, rather than just looking at the code online!
- When approving a PR, provide a reason _why_ you're approving it
  - e.g. "Approving because I tested it locally and all functionality works as expected"
  - e.g. "Approving because the change is simple and matches the Figma design"
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation updates)
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.

2024-07-07 05:51 UTC, OddTomBrooks commented
Do not merge until frontend implementation is integrated into this PR

Failed tests are due to pending frontend implementation

2024-07-09 19:02 UTC, StevenWadeOddball requested changes

2024-07-09 19:05 UTC, StevenWadeOddball commented
I forgot to note! I also verified the email and it looks good, thanks @OddTomBrooks!

2024-07-10 22:57 UTC, OddTomBrooks commented on pkg/models/data_exchange_approach.go
You're correct that this is a placeholder. The true implementation is on feature/EASI-4461_data_exchange_approach. When that branch's PR is finalized I will merge it to main and swap out to the appropriate type at that time.

2024-07-11 03:55 UTC, OddTomBrooks commented on pkg/graph/schema/types/activity.graphql
> +type DataExchangeApproach {
Same note as above. Once the actual Data Exchange Approach implementation is reconciled I will merge and swap in. This stub exists to facilitate hot swapping types later.

2024-07-11 04:21 UTC, OddTomBrooks commented on pkg/notifications/data_exchange_approach_completed.go
> +func ActivityDataExchangeApproachCompletedCreate(
Fun fact, you can't commit files from your git stash. 🤦‍♂️ 

Popped and added.

2024-07-11 13:41 UTC, StevenWadeOddball commented on pkg/models/data_exchange_approach.go
Sounds good. If this merges to a feature branch instead of main, it should be fine to merge now anyways, and the new type can be added at a later time.

2024-07-12 03:53 UTC, OddTomBrooks commented on pkg/graph/resolvers/data_exchange_approach_helper.go
> +	receiverIDs []uuid.UUID,
I thought about this quite a bit and struck a middle ground. I have updated this helper to expect a slice of models.UserAccountAndNotificationPreferences. Based on this input I can efficiently do all downstream notification routing. It likely means a bit of routing / structuring post-integration, but I think that makes the most sense in terms of dividing responsibility and potentially opens the opportunity for some helper method structure to better decouple future form/notif implementations.

2024-07-16 09:47 UTC, merged