[EASI-4501] MDM to MDM-POR Changes
CMSgov/mint-app pull request #1231
Opened 2024-07-17 16:01 UTC by OddTomBrooks

# EASI-4501

## Description

- Renamed `MDM` to `MDM-POR` in migration and gql schema
- Updated translations to match
- Added support for `Trans` component rendered links in timeline
- Updated unit tests

## How to test this change

- Verify name changes match Figma

## PR Author Checklist

- [ ] I have provided a detailed description of the changes in this PR.
- [ ] I have provided clear instructions on how to test the changes in this PR.
- [ ] I have updated tests or written new tests as appropriate in this PR.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines

- It's best to pull the branch locally and test it, rather than just looking at the code online!
- When approving a PR, provide a reason _why_ you're approving it
  - e.g. "Approving because I tested it locally and all functionality works as expected"
  - e.g. "Approving because the change is simple and matches the Figma design"
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation updates)
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.

2024-07-18 20:46 UTC, StevenWadeOddball requested changes
I have not reviewed the front end code, but I wanted to provide some feedback regarding backend migrations.

2024-07-18 20:46 UTC, StevenWadeOddball commented on migrations/V162__Update_MDM_To_MDM_POR.sql
> +    sol_key = 'MDM-POR',
This line (sol_key = 'MDM-POR',) isn't needed, the alter type expression already renames the key.

2024-07-18 20:46 UTC, StevenWadeOddball commented on pkg/graph/schema/types/shared_enums.graphql
> +  MDMPOR
```suggest
MDM_POR
```

2024-07-18 20:46 UTC, StevenWadeOddball commented on pkg/models/possible_operational_solution.go
> +	OpSKMdmPor                    OperationalSolutionKey = "MDMPOR"
```suggest
OpSKMdmPor                    OperationalSolutionKey = "MDM_POR"
````

2024-07-18 20:46 UTC, StevenWadeOddball commented on src/i18n/en-US/modelPlan/solutions.ts
> +      MDMPOR: 'Master Data Management Program-Organization Relationship',
See other notes, I suggest we rename the key to MDM_POR

2024-07-18 20:46 UTC, StevenWadeOddball commented on migrations/V162__Update_MDM_To_MDM_POR.sql
> +ALTER TYPE OPERATIONAL_SOLUTION_KEY RENAME VALUE 'MDM' TO 'MDM-POR';
```suggestion
ALTER TYPE OPERATIONAL_SOLUTION_KEY RENAME VALUE 'MDM' TO 'MDM_POR';
```
I think that `_` might be more consistent

2024-07-22 15:25 UTC, StevenWadeOddball approved these changes
Thanks @patrickseguraoddball and @OddTomBrooks. I made a few simple fixes to the backend code, and verified the frontend matches figma. This should be good to go! Can you please take a quick look at the backend changes I made before merging?

2024-07-22 16:55 UTC, patrickseguraoddball approved these changes

2024-07-24 14:14 UTC, merged