[MINT-2501] Provider physician List Modal
CMSgov/mint-app pull request #1280
Opened 2024-08-05 20:37 UTC by garyjzhao

# MINT-2501

## Description

## How to test this change

1.  

## PR Author Checklist

- [ ] I have provided a detailed description of the changes in this PR.
- [ ] I have provided clear instructions on how to test the changes in this PR.
- [ ] I have updated tests or written new tests as appropriate in this PR.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines

- It's best to pull the branch locally and test it, rather than just looking at the code online!
- When approving a PR, provide a reason _why_ you're approving it
  - e.g. "Approving because I tested it locally and all functionality works as expected"
  - e.g. "Approving because the change is simple and matches the Figma design"
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation updates)
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.

2024-08-06 18:50 UTC, ClayBenson94 reviewed
Changes look good locally!

I was able to find one change that might be worth making - is there any way we could clear the search when the `type` of table changes (like when switching between side-nav items?)

![Kapture 2024-08-06 at 14 51 55](https://github.com/user-attachments/assets/0dc8d2cb-a5f2-47d1-84c6-c0fb52229515)


If that would require any kind of large refactor I'm fine to approve as-is, but thought I'd ask!

2024-08-07 15:11 UTC, patrickseguraoddball requested changes
There doesn't seem to be any navigation elements visible at certain sizes

![Screenshot 2024-08-07 at 9 59 06 AM](https://github.com/user-attachments/assets/9a8010be-8bc9-4cdf-a86c-7c66c06ad7e3)

2024-08-07 15:11 UTC, patrickseguraoddball commented on src/components/TablePagination/index.scss
>      &__page-no {
You have to be really careful about removing styles blanketed across a component.  This is a side affect on another table: 

![Screenshot 2024-08-07 at 10 01 00 AM](https://github.com/user-attachments/assets/ee2b9725-009f-4ee9-b828-6f90265cc350)

2024-08-07 15:11 UTC, patrickseguraoddball commented on src/views/ModelPlan/ReadOnly/_components/Sidenav/index.tsx
> +  isHelpArticle?: boolean;
Why was this changed?  Not saying it's wrong, just not sure why it was made

2024-08-07 15:11 UTC, patrickseguraoddball commented on src/views/ModelPlan/TaskList/ParticipantsAndProviders/_component/ProviderAndSupplierModal/index.tsx
> +  // Table as UswdsTable
Unneeded commented out code

2024-08-07 15:11 UTC, patrickseguraoddball commented on src/views/ModelPlan/TaskList/ParticipantsAndProviders/_component/ProviderAndSupplierModal/index.tsx
> +  );
You can use `geyKeys` here to preserve the type and not need the type assertion `key as ExistingProviderSupplierTypes` I believe.

2024-08-07 15:11 UTC, patrickseguraoddball commented on src/views/ModelPlan/TaskList/ParticipantsAndProviders/_component/ProviderAndSupplierModal/index.tsx
> +              onClick={closeModal}
This has copied over/unused styles and data-testid from discussion center

2024-08-07 15:11 UTC, patrickseguraoddball commented on src/views/ModelPlan/TaskList/ParticipantsAndProviders/_component/ProviderAndSupplierTable/index.tsx
> +    </>
I have a ticket to capture all the conversions of table pagination [MINT-3034](https://jiraent.cms.gov/browse/MINT-3034).  With the latest upgrade to Truss package we now have access to their pagination.  In my last PR I created a hook to merge the component with functionality.  We should standardize all pagination now.  This won't block the PR but just wanted to note this for future visibility.  The mentioned ticket will rewrite this when worked on.  The hook is called `usePagination` and can be referenced by the Models Approaching Clearance PR that was jsut merged

2024-08-07 15:13 UTC, patrickseguraoddball commented
Also a weird overlap here as certain widths, nothing huge

![Screenshot 2024-08-07 at 10 13 32 AM](https://github.com/user-attachments/assets/0395838d-903b-47d6-8292-6cac91957eb6)

2024-08-07 15:15 UTC, patrickseguraoddball commented on src/views/ModelPlan/TaskList/ParticipantsAndProviders/_component/ProviderAndSupplierTable/index.tsx
> +      />
I think should show `31-38 of 38 results`

2024-08-07 15:16 UTC, patrickseguraoddball commented
Spacing here seems a bit tight compared to Figma

![Screenshot 2024-08-07 at 10 16 37 AM](https://github.com/user-attachments/assets/70b9e769-8877-412e-89ba-0bd48c4ffe6f)

2024-08-07 18:36 UTC, garyjzhao commented
@ClayBenson94 

https://github.com/user-attachments/assets/3732b41f-27e2-47f3-b0c0-7d04eed66444

2024-08-07 18:38 UTC, garyjzhao commented on src/components/TableFilter/index.tsx
> +        value={globalFilter ?? ''}
@ClayBenson94 this one liner addressed what you were asking for 🤣


https://github.com/user-attachments/assets/25f02191-46ab-467d-aa4c-934cfa3c6e10

2024-08-08 14:18 UTC, patrickseguraoddball requested changes

2024-08-08 17:27 UTC, garyjzhao commented
@patrickseguraoddball, i just confirmed with Natalie that we can push this to PROD once the work is completed. She will review the feature in PROD.

2024-08-08 19:04 UTC, patrickseguraoddball requested changes
There's some weirdness with the navigation at different sizes.  It goes to select box, then back to the first side nav

![Screenshot 2024-08-08 at 2 03 28 PM](https://github.com/user-attachments/assets/06809b00-7059-41a5-bcc6-75828b1b7b97)

![Screenshot 2024-08-08 at 2 02 36 PM](https://github.com/user-attachments/assets/c33ac6ce-4173-4127-b3c5-98bdf2a2be05)

2024-08-12 12:54 UTC, patrickseguraoddball approved these changes

2024-08-12 14:28 UTC, merged