[NOREF/Combine-Milestones-and-Basics] Front End Implementation of Combining Milestones and Basics
CMSgov/mint-app pull request #168
Opened 2022-08-02 20:07 UTC by garyjzhao

# NOREF

## Changes and Description

- Change 1
- Change 2

## How to test this change

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Tested user-facing changes with voice-over and the [rotor menu](https://support.apple.com/guide/voiceover/with-the-voiceover-rotor-mchlp2719/mac)

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2022-08-03 19:09 UTC, patrickseguraoddball commented
https://github.com/CMSgov/mint-app/blob/d180ad751db4a25e8508693d9018d8db67d3dfa6/src/queries/GetModelPlan.ts#L11-L36

None of these fields are necessary for the task-list, can remove from the query

2022-08-03 19:11 UTC, patrickseguraoddball commented
https://github.com/CMSgov/mint-app/blob/d180ad751db4a25e8508693d9018d8db67d3dfa6/src/views/ModelPlan/TaskList/Basics/Milestones/index.tsx#L587-L598

The conditional check for the error will no never progress to the validation if an error is present.  Should be able to remove this conditional on both the 'Back' and 'Return to task list' submissions

2022-08-03 19:12 UTC, patrickseguraoddball commented
https://github.com/CMSgov/mint-app/blob/d180ad751db4a25e8508693d9018d8db67d3dfa6/src/views/ModelPlan/TaskList/index.tsx#L114-L142

Should be able to deprecate these legacy functions for basics now.

2022-08-03 19:12 UTC, patrickseguraoddball commented
https://github.com/CMSgov/mint-app/blob/d180ad751db4a25e8508693d9018d8db67d3dfa6/src/views/ModelPlan/TaskList/index.tsx#L331-L52

Should also be able to deprecate this conditional for basics

2022-08-03 19:34 UTC, patrickseguraoddball requested changes
Nice Gary, just noted some changes that are need with form submission on milestones.  Also tested locally - all those custom task list functions for basics can be completely removed

2022-08-05 20:05 UTC, garyjzhao commented on src/queries/GetModelPlan.ts
>          status
@patrickseguraoddball Thanks for the review. I had to leave `basics, id, modifiedDts, and status` because Task List needed it to render properly

2022-08-08 15:51 UTC, merged