[EASI-2217] Read-only Model Basics - FE
CMSgov/mint-app pull request #212
Opened 2022-09-14 19:11 UTC by garyjzhao

# EASI-2217

## Changes and Description

- Change 1
- Change 2

## Acceptance Criteria
- Render questions and answers from the task list section
- Should still render unanswered questions - populated with 'No answer entered'
- Testing

## How to test this change

1. Navigate to the Model Summary ( Models on nav > Complete Plan > View this Model Plan on sidebar)
2. Ensure data is displayed correctly and matches figma

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Tested user-facing changes with voice-over and the [rotor menu](https://support.apple.com/guide/voiceover/with-the-voiceover-rotor-mchlp2719/mac)

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2022-09-14 19:18 UTC, garyjzhao commented on src/views/ModelPlan/ReadOnly/ModelBasics/index.scss
> +}
Had to forcefully remove content (the numbers) and adjust its size and alignment to change  the Process List bullets to match figma

|Stock|Modified|
|---|---|
|![image](https://user-images.githubusercontent.com/2349702/190243092-7657c1cc-972a-4c15-8791-10b6aa49733b.png)|![image](https://user-images.githubusercontent.com/2349702/190243223-703a767e-726d-4436-af11-accdfca925e0.png)|

2022-09-15 17:43 UTC, patrickseguraoddball requested changes
Nice work Gary!  I like the component for readonly.  Just some issues with the snapshots and baking in the query data.

2022-09-15 17:43 UTC, patrickseguraoddball commented on src/views/ModelPlan/ReadOnly/ModelBasics/index.test.tsx
> +  });
This snapshot isn't capturing any of the query data.  It's generally a good idea to inspect the snapshot to insure the query data is baked in.  For all snapshot that render async data, you need to await the data before asserting the snapshot.  You need to make sure you await the queried data, and not some static component.

Something like this:

```
await waitFor(() => {
      expect(
        screen.getByTestId('model-category')
      ).toHaveValue('Primary Care');
});

expect(asFragment()).toMatchSnapshot();
```

2022-09-15 17:43 UTC, patrickseguraoddball commented on src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
> +                        Here is a list of things you could try to check and fix:
This snapshot should contain valid data

2022-09-19 12:58 UTC, patrickseguraoddball submitted a review, later dismissed

2022-09-19 17:20 UTC, patrickseguraoddball approved these changes

2022-09-19 17:38 UTC, merged