Easi 2434/mac and init user table
CMSgov/mint-app pull request #316
Opened 2022-11-23 19:25 UTC by StevenWadeOddball

# EASI-2434

## Changes and Description

- Introduce a User Table
    -  Added to the user table at request initialization
    - User Info retrieved from OktaEndpoint and stored in the DB
- Refactor NDA Agreement
   - Table now references the user table instead of EUAID

## How to test this change

1. Log into the App using your OKTA EUID Account
2.  Confirm you can log in and accept the NDA. 
3. Confirm there is a record of your account in the user table
4. If you have a test account with MAC user job codes, log in and repeat the steps for MAC

## Future Improvements
- Eventually, every table can be refactored to use the user table instead of using EUAID
- The user info endpoint is currently being constructed by combining a root URL with `/userinfo`, the actual endpoint is exposed in the frontend token, but not the backend token. It would be more ideal to get the full endpoint from there.

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2022-11-28 16:22 UTC, patrickseguraoddball commented
This works as expected and I can verify my record in `user_account` table!

2022-11-29 00:14 UTC, OddTomBrooks requested changes

2022-11-29 00:14 UTC, OddTomBrooks commented on pkg/local/authentication_middleware.go
> +	userAccount, err := userhelpers.GetOrCreateUserAccount(store, princ.ID(), true, "", "", princ.JobCodeMAC) //TODO, do we need to do anything with the user? Should we pass the id around?
Is this TODO still relevant?

2022-11-29 00:14 UTC, OddTomBrooks commented on pkg/models/nda_agreement.go
> +	//TODO removing baseStruct for this temporarily
TODO still relevant?

2022-11-29 00:14 UTC, OddTomBrooks commented on pkg/okta/authentication_middleware.go
> +type EnhancedJwt struct { //TODO rename this to something logical, and return it
TODO still relevant?

2022-11-29 00:14 UTC, OddTomBrooks commented on pkg/server/routes.go
> +	// }
Is there any reason to keep this?

2022-11-29 00:14 UTC, OddTomBrooks commented on pkg/storage/user_accountStore.go
> +	// TODO work in progress
Is this still a WIP?

2022-11-29 00:14 UTC, OddTomBrooks commented on pkg/storage/user_accountStore.go
> +	// TODO work in progress
Is this still a WIP?

2022-11-29 00:14 UTC, OddTomBrooks commented on pkg/userhelpers/user_account_utils.go
> +	//TODO deserialize to another struct. Do we want another
Is this TODO still relevant?

2022-11-29 21:53 UTC, StevenWadeOddball commented on pkg/graph/resolvers/resolver_test.go
> +	// suite.testConfigs.Principal = getTestPrincipal(suite.testConfigs.Store, suite.testConfigs.UserInfo.EuaUserID)
removed old comments

2022-11-29 21:53 UTC, StevenWadeOddball commented on pkg/local/authentication_middleware.go
> +	userAccount, err := userhelpers.GetOrCreateUserAccount(store, princ.ID(), true, "", "", princ.JobCodeMAC) //TODO, do we need to do anything with the user? Should we pass the id around?
removed old comments

2022-11-29 22:04 UTC, OddTomBrooks approved these changes
Great work Steven!

2022-11-29 22:26 UTC, merged