[EASI-2521] Discussion and Discussion Reply return user info full stack
CMSgov/mint-app pull request #388
Opened 2023-01-06 17:17 UTC by OddTomBrooks

# EASI-2521

## Changes and Description

- Added UserInfo to Discussion
- Added UserInfo to DiscussionReply

## How to test this change

- Create a Discussion, observe that CreatedByUserInfo populates appropriately and ModifiedByUserInfo is nil
- Update a Discussion, observe that CreatedByUserInfo populates without change and ModifiedByUserInfo populates appropriately
- Create a DiscussionReply, observe that CreatedByUserInfo populates appropriately and ModifiedByUserInfo is nil
- Update a DiscussionReply, observe that CreatedByUserInfo populatese without change and ModifiedByUserInfo populates appropriately

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2023-01-09 19:23 UTC, ClayBenson94 requested changes
I think these changes work for the areas they touched, but a few things are missing that might be worth considering our approach:

- It doesn't look like the resolvers that fetch discussions & replies are returning this data.
- Since the model defines these properties and the resolvers (i.e. `CreatePlanDiscussion()`) are implementing the fetch, it means that we're fetching this information every time we call one of these resolvers, even if it's not requested in the GQL

For those reasons, I think it might be worth approaching this from the angle where we don't include these properties in the model in `pkg/models`, and instead implement resolvers that make this call to CEDAR LDAP only when it's requested.

This has the added benefit of only having to implement the 2 new resolvers, rather than having to add the fetch logic to each existing resolver.

2023-01-09 19:23 UTC, ClayBenson94 commented on pkg/models/plan_discussion.go
> +	ModifiedByUserInfo *UserInfo        `json:"modifiedByUserInfo" db:"modified_by_user_info"`
I think it might end up being less overall code to not have these 2 fields added to the model, but just let GQL resolvers fill them out

2023-01-11 18:21 UTC, StevenWadeOddball requested changes
So our conversation doesn't' get lost, I agree with the points Clay brought up. I think it would be simplest and most consistent to use the graphql resolvers for user info at this point.

2023-01-12 19:51 UTC, StevenWadeOddball commented
PR is being closed in favor of https://github.com/CMSgov/mint-app/pull/397

2023-01-12 19:51 UTC, closed without merging