EASI-1465/craco-uswds-upgrade
CMSgov/mint-app pull request #396
Opened 2023-01-12 15:10 UTC by patrickseguraoddball

# EASI-1465

## Changes and Description

- Upgraded to USWDS 3.3.0
- Upgraded to CRACO 7.0
- Upgraded react-scripts (CRA)
- Upgraded a few other packages for compatibility
- Removed craco-sass-resource-loader
- Removed old uswds theme package
- Adjust craco.config.js to compile new uswds 3.0
- Updated style entry point (index.scss) to import only used packages for better compile
- Imported uswds core in all stylesheet that utilized themes, functions, mixins, etc.
- Deprecated uswdsUtilities.scss

No snapshots needed to be updated!

## Outstanding work:
eslint has some compatibility issues with nested dependencies for 
`ERROR in [eslint] Plugin "import" was conflicted between ".eslintrc » eslint-config-airbnb » /app/node_modules/eslint-config-airbnb-base/index.js » /app/node_modules/eslint-config-airbnb-base/rules/imports.js" and ".eslintrc » eslint-config-react-app".`

Additionally docker is killing the FE process/container on some recompiles.  Not sure why this happens sometimes, but is enough to affect development.

I was decided to PoC on MINT for familiarity, but this upgrade can easily be adapted on EASI.

## How to test this change

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2023-01-12 16:09 UTC, DylanSpOddball commented
It looks from the new `craco.config.js` that you're just using it to specify `includePaths`. The [CRA docs](https://create-react-app.dev/docs/adding-a-sass-stylesheet/) mention that you can set a `SASS_PATH` environment variable as a path to import modules from (i.e. `./src/stylesheets`), and use a `~` prefix to implement from `node_modules`. If you set `SASS_PATH` in the `.envrc` file and used `~` for `@use` statements pulling from `node_modules` (i.e. `@use '~uswds-core;'`), would that allow getting rid of Craco? Admittedly, I don't know if you still need it for other assets, like you mentioned working on in today (Thursday's) standup.

2023-01-12 20:34 UTC, patrickseguraoddball commented
> It looks from the new `craco.config.js` that you're just using it to specify `includePaths`. The [CRA docs](https://create-react-app.dev/docs/adding-a-sass-stylesheet/) mention that you can set a `SASS_PATH` environment variable as a path to import modules from (i.e. `./src/stylesheets`), and use a `~` prefix to implement from `node_modules`. If you set `SASS_PATH` in the `.envrc` file and used `~` for `@use` statements pulling from `node_modules` (i.e. `@use '~uswds-core;'`), would that allow getting rid of Craco? Admittedly, I don't know if you still need it for other assets, like you mentioned working on in today (Thursday's) standup.

I gave it a shot but was running into the same issues outlined in this thread with using `SASS_PATH`

https://github.com/facebook/create-react-app/issues/12329

Most of the people ended up scrapping it.

2023-01-17 15:24 UTC, patrickseguraoddball commented
Tests that require the three imported icons in `src/components/UsGovBanner/index.tsx` are failing.  I suspect it's because the USWDS alias's the path where the icons are stored after compilation.  Eslint does not recognize this alias, and there seems to be a discrepancy between eslint and the webpack compiler.

Importing from `@uswds/uswds/src/img/icon-dot-gov.svg` fulfills the compiler (recognizes the alias) but fails the linter
Importing from `@uswds/uswds/dist/img/icon-dot-gov.svg` fails the compiler (alias not needed) and passes the linter

2023-01-17 19:11 UTC, ClayBenson94 requested changes

2023-01-17 19:11 UTC, ClayBenson94 commented on src/components/Header/index.tsx
> +// import UsGovBanner from 'components/UsGovBanner';
Can we remove this commented code now that the source component is gone?

2023-01-17 19:11 UTC, ClayBenson94 commented on src/hooks/useCheckMobile.tsx
> +};
Did something change with being able to import these viewports here? Looks like all the values are right in the viewports.scss file

2023-01-17 20:03 UTC, ClayBenson94 approved these changes
Changes look good!

2023-01-17 20:04 UTC, merged