[EASI 2429] Operational Needs, Operational Solution Access control
CMSgov/mint-app pull request #408
Opened 2023-01-20 21:18 UTC by rileyanderson

# EASI-2429

## Changes and Description

- Change 1
- Change 2

## How to test this change

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2023-01-23 17:43 UTC, StevenWadeOddball reviewed
something to note, document solution link should probably use the solution link relation

2023-01-23 19:10 UTC, rileyanderson commented
> something to note, document solution link should probably use the solution link relation

@StevenWadeOddball [It does](https://github.com/CMSgov/mint-app/blob/main/pkg/models/plan_document_solution_link.go#L8). It was already there 😄

2023-01-24 15:38 UTC, StevenWadeOddball requested changes
Overall looks pretty good! There are a few places where pre-update still need to be enabled so access control works ( EG Operational_Solution.go (resolvers), the call to BaseStruct Preupdate should provide true instead of false for check access. 

I will make these updates.

2023-01-24 15:38 UTC, StevenWadeOddball commented on pkg/models/operational_solution.go
>  	OperationalNeedID uuid.UUID               `json:"operationalNeedID" db:"operational_need_id"`
This should be removed, as the OperationalNeedID field comes from the embedded struct already, so this is redundant.

2023-01-24 15:43 UTC, StevenWadeOddball commented on pkg/models/operational_solution.go
>  	OperationalNeedID uuid.UUID               `json:"operationalNeedID" db:"operational_need_id"`
When you run the code, one of the variables stays null unless you set it 
![image](https://user-images.githubusercontent.com/99294987/214339488-5905d330-4369-4ca9-93e9-87849759af9c.png)

2023-01-24 15:54 UTC, StevenWadeOddball commented on pkg/models/operational_solution.go
>  	OperationalNeedID uuid.UUID               `json:"operationalNeedID" db:"operational_need_id"`
This is corrected removing the extraneous field
![image](https://user-images.githubusercontent.com/99294987/214342072-3127958c-fd97-44c8-87e2-a7032053a429.png)

2023-01-24 21:19 UTC, StevenWadeOddball commented on pkg/models/operational_solution.go
>  	OperationalNeedID uuid.UUID               `json:"operationalNeedID" db:"operational_need_id"`
I resolved this

2023-01-24 21:20 UTC, StevenWadeOddball commented
@OddTomBrooks and @ClayBenson94 , can you please review this when you have a chance? I made enough changes that I think it should get approval from you two instead of me. It's ready for review.

2023-01-25 19:40 UTC, ClayBenson94 approved these changes

2023-01-25 20:52 UTC, StevenWadeOddball approved these changes

2023-01-25 21:05 UTC, merged