Easi 2702/clear cloudfront cache
CMSgov/mint-app pull request #494
Opened 2023-03-08 18:00 UTC by azeez-salu

# EASI-2702

## Changes and Description

- Created script to clear CloudFront cache
- Updated deploy_to_environment file

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2023-03-08 19:52 UTC, ClayBenson94 requested changes

2023-03-08 19:52 UTC, ClayBenson94 commented on .github/workflows/deploy_to_environment.yml
> +          DISTRIBUTION_ID: ${{ inputs.env }}
What does setting this env do here?

2023-03-08 19:52 UTC, ClayBenson94 commented on scripts/invalidate_cloudfront_cache.sh
> +echo "CloudFront cache invalidation started for distribution $DISTRIBUTION_ID"
Do you think it's worth capturing the invalidation ID as a response, and waiting for the invalidation to be complete before returning?

(i.e. using something like [aws cloudfront wait](https://docs.aws.amazon.com/cli/latest/reference/cloudfront/wait/invalidation-completed.html)?)

2023-03-13 18:15 UTC, Jdwoodson approved these changes
LGTM

2023-03-13 18:32 UTC, ClayBenson94 approved these changes

2023-03-13 19:19 UTC, merged