[EASI-2605] Front End work for Treat as Other Operational Solution
CMSgov/mint-app pull request #543
Opened 2023-04-18 18:51 UTC by garyjzhao

# EASI-2605

## Changes and Description

- this is the same as #542, but with a clean branch off from main

- Deprecate rendering custom solution card on AddCustom view
- `treatAsOther` will be a boolean field on possible AND actual solutions, will not appear on custom solutions
- For this `treatAsOther` solutions outlined [here](https://www.figma.com/file/BcI7pNwfkmwaDD2EGGTsYC/IT-Lead?node-id=1089%3A175128&t=cPbn5sFgs1EBFGHD-0) and [here](https://www.figma.com/file/BcI7pNwfkmwaDD2EGGTsYC/IT-Lead?node-id=415%3A164083&t=cPbn5sFgs1EBFGHD-0) when selecting these from AddSolution view, render the same button below as if you selected 'Other'.  
    - This should take them to the AddCustomSolution view where they can fill out details
- Updated AddCustomSolution view with updated verbiage to account for additional custom types
- Verbiage is dependent on the type of custom solution they selected
- Testing

## How to test this change

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2023-04-24 14:38 UTC, patrickseguraoddball requested changes
Nice Gary :) 

This translation does not render correctly.
![Screenshot 2023-04-24 at 10 23 42 AM](https://user-images.githubusercontent.com/95709965/234025936-b3a10a21-67d5-4492-bca4-a4293499cb04.png)

For solutions that are custom, there should be no `About this solution` link
![Screenshot 2023-04-24 at 10 26 39 AM](https://user-images.githubusercontent.com/95709965/234026789-422581cf-f5a6-430e-ad83-294fd368be25.png)

Selecting "Cross model contract" added two duplicated solutions, with different renderings
![Screenshot 2023-04-24 at 10 27 29 AM](https://user-images.githubusercontent.com/95709965/234027035-c9345fc8-5710-4b00-97ad-df851a82f3a3.png)

There's some funkiness in with the possible needs.  Just want to note I covered this in https://github.com/CMSgov/mint-app/pull/534 that is still in review.
![Screenshot 2023-04-24 at 10 29 47 AM](https://user-images.githubusercontent.com/95709965/234027681-27c016e6-058c-4d8d-9661-aeb48d09dbd2.png)

Adding one of the custom solutions does not bring me to the custom solution screen, it automatically adds it as a regular solution.  These solutions should be treated as other

```
  | OperationalSolutionKey.CONTRACTOR
  | OperationalSolutionKey.CROSS_MODEL_CONTRACT
  | OperationalSolutionKey.EXISTING_CMS_DATA_AND_PROCESS
  | OperationalSolutionKey.INTERNAL_STAFF
  | OperationalSolutionKey.OTHER_NEW_PROCESS;
  ```
![Screenshot 2023-04-24 at 10 33 52 AM](https://user-images.githubusercontent.com/95709965/234028806-eb430b5f-d3b9-427e-8bf7-0a720d44ac7b.png)

2023-04-24 14:38 UTC, patrickseguraoddball commented on src/views/ModelPlan/TaskList/ITSolutions/AddSolution/index.tsx
> +                                OperationalSolutionKey.OTHER_NEW_PROCESS) &&
I think there is a solution missing from here.  Also I think we can probably condense this to have an entity containing all the `other` enums and perform `.includes(value.key)`

2023-04-24 14:38 UTC, patrickseguraoddball commented on src/views/ModelPlan/TaskList/ITSolutions/_components/CheckboxCard/index.tsx
> +            <>
Should this include all the `other` types or just these 3?

2023-04-28 14:51 UTC, patrickseguraoddball requested changes
I think this card still needs to read `Add details` and route them to the custom page

![Screenshot 2023-04-28 at 10 51 31 AM](https://user-images.githubusercontent.com/95709965/235180732-869f882c-452d-4471-ba63-28407d123b62.png)

https://www.figma.com/file/BcI7pNwfkmwaDD2EGGTsYC/IT-Lead?node-id=1057-169006&t=TpiREdHbk7ZDEfx3-0

2023-04-28 14:53 UTC, patrickseguraoddball requested changes
I got this error app crash when pressing back on the browser from the /add-solution page to the /select-solution page

![Screenshot 2023-04-28 at 10 52 26 AM](https://user-images.githubusercontent.com/95709965/235180934-625db7d4-f901-4de3-b157-b856258fc146.png)

2023-04-28 14:54 UTC, patrickseguraoddball commented
I was also still getting instances of solution that weren't selected showing up randomly on `/solution-implementation-details`

2023-05-03 17:29 UTC, patrickseguraoddball requested changes

2023-05-03 17:29 UTC, patrickseguraoddball commented on src/views/ModelPlan/TaskList/ITSolutions/SolutionImplementation/index.tsx
> +
This destructuring needs to be addressed in `SelectSolutions` as well

2023-05-03 17:33 UTC, patrickseguraoddball requested changes

2023-05-03 17:33 UTC, patrickseguraoddball commented on src/views/ModelPlan/TaskList/ITSolutions/AddCustomSolution/index.tsx
> +
This shouldn't be destructured here as well

2023-05-03 17:35 UTC, patrickseguraoddball commented
I'm also a bit torn on whether to use location state at all to pass state between routes.  I think a more consistent method would be to append query params to the route to ensure that on app refresh/redirect the state is persisted.  If you want to leave this out that might be okay, but we should ticket it as tech debt?

2023-05-03 17:53 UTC, garyjzhao commented
Tech debt created to address using query params, instead of location state: https://jiraent.cms.gov/browse/EASI-2898

2023-05-03 18:43 UTC, patrickseguraoddball requested changes
When I added "Internal staff" as a custom solution, then chose to "Add details" to it, it create an entirely new solution instead of adding details to "Internal staff"

![Screenshot 2023-05-03 at 2 43 23 PM](https://user-images.githubusercontent.com/95709965/236013392-266239c4-b97c-496f-8de9-57e5ca3d06ef.png)

2023-05-03 19:28 UTC, patrickseguraoddball requested changes
It's possible for solutions to have identical keys with the ability to re-add the same solution.  React throwing the duplicate key error:

![Screenshot 2023-05-03 at 3 24 44 PM](https://user-images.githubusercontent.com/95709965/236023387-ec4af144-88e5-4149-927d-eafb00f0b77e.png)

![Screenshot 2023-05-03 at 3 24 33 PM](https://user-images.githubusercontent.com/95709965/236023329-40f769ed-1139-4d00-a504-5eb150266a3e.png)

Also getting these new console errors on the Add Custom solution detail page

![Screenshot 2023-05-03 at 3 27 57 PM](https://user-images.githubusercontent.com/95709965/236024272-b328c809-9fd2-4394-854b-55d62cca086e.png)

2023-05-08 15:27 UTC, patrickseguraoddball requested changes
I think the point of contact needs to be hidden if there is no point of contact.  Also the email icon is rendered with no email

![Screenshot 2023-05-08 at 11 25 38 AM](https://user-images.githubusercontent.com/95709965/236864436-057b4605-a095-432d-b29e-cd621e57ee77.png)

![Screenshot 2023-05-08 at 11 25 26 AM](https://user-images.githubusercontent.com/95709965/236864402-862ec11c-0cba-48cd-9eea-b46d40d606ed.png)

2023-05-08 20:42 UTC, patrickseguraoddball submitted a review, later dismissed
The `otherHeader` isn't being shown here after I populate it in AddCustom.

![Screenshot 2023-05-08 at 4 40 45 PM](https://user-images.githubusercontent.com/95709965/236930236-5faae056-894a-40cb-8340-a8f4c19c334a.png)

2023-05-08 20:42 UTC, patrickseguraoddball commented on src/views/ModelPlan/TaskList/ITSolutions/_components/CheckboxCard/index.tsx
> +              )}
This conditional doesn't all for a rendering of both a default solution and a custom solution, which is what `Contractor` is for `Helpdesk support`

2023-05-09 13:47 UTC, patrickseguraoddball approved these changes

2023-05-09 13:47 UTC, merged