[EASI-2609] Addressing 508 findings
CMSgov/mint-app pull request #546
Opened 2023-04-21 18:24 UTC by garyjzhao

# EASI-2609

## Changes and Description

- Add various aria tags to different components mentioned in the Findings document

## How to test this change

- verify screen reader is reading out the accessibiltiy things mentioned in the doc

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2023-04-24 15:24 UTC, patrickseguraoddball requested changes
Thanks for addressing these Gary.

At the time of these findings, IT Solutions help center wasn't implemented, and could use some better aria-labeling.  

`Learn more` links
![Screenshot 2023-04-24 at 11 01 10 AM](https://user-images.githubusercontent.com/95709965/234036533-a4daba12-01f1-44a3-a074-b65cf05b857b.png)

`Category tags`
![Screenshot 2023-04-24 at 11 01 44 AM](https://user-images.githubusercontent.com/95709965/234036682-5aae3f22-9004-4da7-b532-9f0c45b9d82c.png)

`About this solution links`
![Screenshot 2023-04-24 at 11 02 05 AM](https://user-images.githubusercontent.com/95709965/234036765-4f2907b7-5815-424f-a609-62a187c2abf0.png)

This no results item has no tabIndex/ not tabbable
<img width="396" alt="Screenshot 2023-04-24 at 11 04 54 AM" src="https://user-images.githubusercontent.com/95709965/234037430-a770467d-5899-4032-a651-9278c1801abf.png">

I think the star buttons should have a unique label, maybe the model plan name appended to the end
![Screenshot 2023-04-24 at 11 21 17 AM](https://user-images.githubusercontent.com/95709965/234041918-178a15e5-3ddc-4509-b572-4e7e9b71ff52.png)

I think the results of seach need an `aria-live` attribute for screen readers to announce results
![Screenshot 2023-04-24 at 11 22 49 AM](https://user-images.githubusercontent.com/95709965/234042305-d43ac67b-d091-430e-bb37-7d9adc8d7b97.png)

2023-05-01 13:43 UTC, ClayBenson94 requested changes

2023-05-01 13:43 UTC, ClayBenson94 commented on src/views/ModelPlan/TaskList/OpsEvalAndLearning/Evaluation/__snapshots__/index.test.tsx.snap
> +        id="ops-eval-and-learning-data-to-send"
I think adding this ID makes us have 2 IDs that are the same on this page: https://github.com/CMSgov/mint-app/blob/6ec9517315c4e0963e7e3fbfa45acb2b6c1b95c8/src/views/ModelPlan/TaskList/OpsEvalAndLearning/Evaluation/index.tsx#L517

I think that's what's breaking the E2E test here https://github.com/CMSgov/mint-app/blob/6ec9517315c4e0963e7e3fbfa45acb2b6c1b95c8/cypress/e2e/opsEvalAndLearning.spec.js#L285-L287


![image](https://user-images.githubusercontent.com/15203744/235460081-753f2aeb-406b-4ecf-a747-969c26f7898d.png)

2023-05-01 19:06 UTC, patrickseguraoddball requested changes
Thanks Gary, just two outstanding things

There should be a tabindex on the text that reads `No results` here, so it is tabbable, but not selectable.  Might need to look into the library docs for adjusting this functionality

![Screenshot 2023-05-01 at 3 02 43 PM](https://user-images.githubusercontent.com/95709965/235511999-493ac20a-930d-4523-8cc9-957c3f444ad8.png)

There should be an aria-live label on this warning if no results are found from the query
![Screenshot 2023-05-01 at 3 04 38 PM](https://user-images.githubusercontent.com/95709965/235512291-21c70fcb-13d9-4f33-87bd-5e52341b1b27.png)

2023-05-03 17:41 UTC, patrickseguraoddball approved these changes
LG

2023-05-03 17:42 UTC, merged