[EASI-3000] Read View Users Contribute Discussions
CMSgov/mint-app pull request #596
Opened 2023-06-16 16:02 UTC by OddTomBrooks

# EASI-3000

## Changes and Description

- Read-only users can create a discussion
- Users can select a role when creating a discussion
- The `mostRecentDiscussionRoleSelection` returns the most recent role selection for a user

## How to test this change

- Run `scripts/dev down && scripts/dev up:backend && scripts/dev db:seed`
  - Assert that a user_role column has been added to the `plan_discussion` table
- Initialize model plan variables using standard endpoints
- Create a user discussion
- Run the `mostRecentDiscussionRoleSelection` endpoint
  - Assert that the most recent user role selection matches with the most recent created or modified entry in the database

## PR Author Review Checklist

- [x] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [x] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2023-06-21 14:01 UTC, ClayBenson94 requested changes

2023-06-21 14:55 UTC, OddTomBrooks commented on migrations/V95__Update_Model_Plan_Abbreviation.sql
This feature branch was created off of the previous feature branch to reduce merge work. You are correct that this file should be reverted to the main revision and whitespace changes ignored.

2023-06-21 14:56 UTC, OddTomBrooks commented on pkg/storage/plan_discussionStore.go
> +	print("GetLatestDiscussionRoleSelection test\n\n")
Yep! Ghost debug code. Good catch.

2023-06-27 15:34 UTC, ClayBenson94 submitted a review, later dismissed

2023-06-27 17:21 UTC, patrickseguraoddball submitted a review, later dismissed
I think there needs to be userRole and useRoleDescription on replies as well.

2023-06-27 17:32 UTC, OddTomBrooks commented
> I think there needs to be userRole and useRoleDescription on replies as well.

Ok. On it.

2023-06-27 19:35 UTC, patrickseguraoddball commented
Is `mostRecentDiscussionRoleSelection` return value something we could have on the modelPlan itself?  Having to make a separate query each time is doable, but this would alleviate a lot of overhead for the FE.  If it was a field on the model plan that we could query would be awesome

2023-06-27 19:39 UTC, OddTomBrooks commented
> Is `mostRecentDiscussionRoleSelection` return value something we could have on the modelPlan itself? Having to make a separate query each time is doable, but this would alleviate a lot of overhead for the FE. If it was a field on the model plan that we could query when we fetch the modelPlan/discussions would be awesome

It's doable. This introduces a pseudo-statefulness which is probably fine, but I'd like to discuss it with @ClayBenson94 tomorrow to make sure that's something we'd like to do from an architectural standpoint. As it stands, the most recent discussion role selection is a value calculated from a database query.

The total lift on this is fairly minor, so if Clay is fine with it I'll make the change tomorrow.

2023-07-03 17:42 UTC, OddTomBrooks commented
Smoke testing works as expected. No issues noticed.

2023-07-03 19:01 UTC, ClayBenson94 approved these changes

2023-07-03 19:22 UTC, merged