EASI-2713 Email notif on model plan dates changed
CMSgov/mint-app pull request #609
Opened 2023-06-27 15:36 UTC by OddTomBrooks

# EASI-2713

## Changes and Description

- Add email notifications when model plan dates change

## How to test this change

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2023-06-28 01:34 UTC, OddTomBrooks commented
In order to avoid merge issues, this PR contains changes from the feature branch `EASI-3000/read_view_users_contribute_discussions`. Please ignore changes related to user roles as those changes will disappear once the feature branch is merged to main.

2023-07-11 18:39 UTC, ClayBenson94 requested changes

2023-07-11 18:39 UTC, ClayBenson94 commented on cmd/dbseed/main.go
> +	s.createEmailRecipientModelDatesChanged("two@test.gov")
Are these wrapers (and associated store methods) still needed now that we're configuring recipients by env vars?

2023-07-11 18:39 UTC, ClayBenson94 commented on pkg/graph/resolvers/plan_basics.go
> +		"wrapUpEnds":              "Model wrap-up end date",
This feels similar / duplicative to what's in getDateFieldsToCheck. Would it be possible to use this map for both purposes? ([You can iterate over the keys of a map](https://goplay.tools/snippet/TlQMdVWPHA6), which might mean this function could be used to get the list of field names to check as well)

2023-07-11 18:39 UTC, ClayBenson94 commented on pkg/storage/SQL/model_plan_date_changed_email_recipients/create.sql
Same comment from above - we can probably get rid of this file, right?

2023-07-11 18:39 UTC, ClayBenson94 commented on pkg/storage/SQL/model_plan_date_changed_email_recipients/get.sql
Same comment from above - we can probably get rid of this file, right?

2023-07-11 18:39 UTC, ClayBenson94 commented on pkg/storage/model_plan_date_changed_email_recipientsStore.go
Same comment from above - we can probably get rid of this file, right?

2023-07-11 22:05 UTC, StevenWadeOddball requested changes
Thanks @OddTomBrooks , I had some weird behavior when I was testing this locally. It doesn't always recognize that a date is different than it was previously.  For example, if I have a complete ICIP date set, and I change it again to another date in the future, no email fires. I also confirmed with breakpoints in the code that the no date changes register. 

The email that did fire off looks like it might be getting the wrong data (eg providing the same date twice?)

![image](https://github.com/CMSgov/mint-app/assets/99294987/6752bdc0-703f-4134-a6e1-5a90468dc62d)


Could you please take a look at the date comparison logic?  I think that would be a good place to add Unit tests to verify that this functionality is behaving as expected. 

Also, to verify, are all the store functions referencing an earlier approach which stored users in the database?

2023-07-11 22:07 UTC, StevenWadeOddball commented on pkg/graph/resolvers/plan_basics_helper.go
> +func NewDateProcessor(changes map[string]interface{}, existing *models.PlanBasics) (*DateProcessor, error) {
For what it's worth, you could use some table driven testing to validate the permutations that you mentioned above for manual testing. I think that be worthwhile.

2023-07-12 17:11 UTC, OddTomBrooks commented on pkg/graph/resolvers/plan_basics_helper.go
> +func NewDateProcessor(changes map[string]interface{}, existing *models.PlanBasics) (*DateProcessor, error) {
This is a great point. As this logic has been abstracted from the resolver it is unit testable.

2023-07-12 17:23 UTC, OddTomBrooks commented
> Thanks @OddTomBrooks , I had some weird behavior when I was testing this locally. It doesn't always recognize that a date is different than it was previously. For example, if I have a complete ICIP date set, and I change it again to another date in the future, no email fires. I also confirmed with breakpoints in the code that the no date changes register.
> 
> The email that did fire off looks like it might be getting the wrong data (eg providing the same date twice?)
> 
> ![image](https://user-images.githubusercontent.com/99294987/252805922-6752bdc0-703f-4134-a6e1-5a90468dc62d.png)
> 
> Could you please take a look at the date comparison logic? I think that would be a good place to add Unit tests to verify that this functionality is behaving as expected.
> 
> Also, to verify, are all the store functions referencing an earlier approach which stored users in the database?

Strange, I have not seen such behaviour during local testing. Thank you for identifying this problem, I will go through this thoroughly to determine the root cause. Perhaps it will be exposed during construction of unit tests.

2023-07-20 18:16 UTC, ClayBenson94 requested changes
![image](https://github.com/CMSgov/mint-app/assets/15203744/a0e52c94-ff0a-49d9-ad9b-aca4910c961f)

Tested locally - looks like, at least for the ICIP date, it's showing the new date in both the old and new fields. Not sure if this is in the tested functions or not, or if it's cropping up somewhere else (like in the templates?)

2023-07-20 19:02 UTC, OddTomBrooks commented
> ![image](https://user-images.githubusercontent.com/15203744/254972957-a0e52c94-ff0a-49d9-ad9b-aca4910c961f.png)
> 
> Tested locally - looks like, at least for the ICIP date, it's showing the new date in both the old and new fields. Not sure if this is in the tested functions or not, or if it's cropping up somewhere else (like in the templates?)


@ClayBenson94 
I'm struggling to reproduce this issue.

![image](https://github.com/CMSgov/mint-app/assets/100007843/9b962417-2f9f-476f-8044-7b600c2eb2a8)
![image](https://github.com/CMSgov/mint-app/assets/100007843/7c81c08c-2eeb-4e9d-b369-28b37ecbe76e)
![image](https://github.com/CMSgov/mint-app/assets/100007843/1b2419f1-4670-471f-896b-2c29b8982c0b)
![image](https://github.com/CMSgov/mint-app/assets/100007843/6c5c5739-76e6-498a-8207-fd8f96a1bbeb)


Can you repro it? If so, can you provide the repro steps?
It might be based on initial values. In that case, which model plan are you modifying?

Also, as a sanity check, do you have latest and did you rebuild your containers?

2023-07-21 13:53 UTC, ClayBenson94 approved these changes

2023-07-24 06:33 UTC, merged