[EASI-3131] Threaded Discussions
CMSgov/mint-app pull request #703
Opened 2023-09-19 13:44 UTC by OddTomBrooks

# EASI-3131

## Changes and Description

- Removed DiscussionStatus enum from schema
- Removed Resolution from DiscussionReply
- Updated most front-end references

## How to test this change

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2023-09-20 14:26 UTC, StevenWadeOddball reviewed
Thanks Tom, I know it's still in draft, but I figured I'd take a look since the timing worked out well for me. The backend looks pretty good! The only thing I noticed is that Discussion status is only removed from `GQL`, and still exists in `GO` and the `DB`.

2023-09-20 14:26 UTC, StevenWadeOddball commented on pkg/graph/schema.graphql
> -  status: DiscussionStatus
Discussion status still exists in the `GO` struct and in the database. This should probably be removed like it was for the reply.

2023-09-28 17:31 UTC, garyjzhao commented
@patrickseguraoddball we merged in the FE work into this branch. if it helps, this is the [OG PR](https://github.com/CMSgov/mint-app/pull/719)

2023-09-28 18:44 UTC, StevenWadeOddball requested changes
@OddTomBrooks , this looks looks good overall. Could you please update the postman collection? I also did a quick functional test on the front end and it worked as expected.

2023-09-28 18:44 UTC, StevenWadeOddball commented on MINT.postman_collection.json
@OddTomBrooks , could you update postman please? I think something might have gotten messed up. The only changed field is the exporter. However, the discussion and discussion reply queries don't work right now because they have extra fields (`status` and `isResolution`)

2023-09-29 13:36 UTC, ClayBenson94 approved these changes
Changes work locally, looks great! Thanks @OddTomBrooks and @garyjzhao !

2023-09-29 13:50 UTC, StevenWadeOddball approved these changes

2023-09-29 18:03 UTC, merged