[EASI-3675] FE Work for EASI-3629
CMSgov/mint-app pull request #867
Opened 2023-12-19 18:23 UTC by garyjzhao

# EASI-3675

## Changes and Description

- Change 1
- Change 2

## How to test this change

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2023-12-29 16:10 UTC, patrickseguraoddball requested changes
Nice Gary

I'm going to request some changes pending on a different PR that will addressed some unwanted behavior with the ordering of the values for your work.

Here is the explanation of the issue and the work - [https://github.com/CMSgov/mint-app/pull/877](https://github.com/CMSgov/mint-app/pull/877)

Here is an example of the incorrect ordering

![Screenshot 2023-12-29 at 10 12 58 AM](https://github.com/CMSgov/mint-app/assets/95709965/0285d689-713f-4842-964a-9e3ee6affebb)

2023-12-29 16:19 UTC, patrickseguraoddball commented
One other thing to note - I see you fixed the bullet not rendering on the readonly.  I like your style solution to this over the one I fixed in main - [https://github.com/CMSgov/mint-app/pull/870](https://github.com/CMSgov/mint-app/pull/870).  Then main get's merged into this, will most likely be a merge conflict.  Feel free to choose/merge your solution over mine!

2024-01-02 16:58 UTC, StevenWadeOddball commented
@garyjzhao, can you update the feature branch with main, and then merge the feature branch into this branch? When you merge the main branch into this branch based off of a feature, it can result in incorrect GIT history.

2024-01-02 18:26 UTC, patrickseguraoddball requested changes

2024-01-02 18:26 UTC, patrickseguraoddball commented on src/utils/modelPlan.ts
>  // Sort possible operational needs
We no longer need this util if we are using the sort from the translations

2024-01-02 19:21 UTC, patrickseguraoddball approved these changes
LG!

2024-01-02 20:43 UTC, merged