[EASI-3738] FE work for geography questions updates
CMSgov/mint-app pull request #890
Opened 2024-01-08 18:07 UTC by garyjzhao

# EASI-3738

## Changes and Description

- Change 1
- Change 2

## How to test this change

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2024-01-11 15:31 UTC, StevenWadeOddball commented
@garyjzhao, is this just meant to be front end changes? Or front end and backend changes?

2024-01-11 17:31 UTC, patrickseguraoddball requested changes
Nice work Gary

The new data needs to be added to both queries and file for CSV.  Currently `geographiesStatesAndTerritories` and `geographiesRegionTypes` are missing

2024-01-11 17:31 UTC, patrickseguraoddball commented on src/data/mock/readonly.ts
> +  geographiesRegionTypes: [],
Not a huge deal, but for these readonly tests, it's useful to always try to populate data for the snapshots

2024-01-11 17:31 UTC, patrickseguraoddball commented on src/views/ModelPlan/TaskList/GeneralCharacteristics/TargetsAndOptions/index.tsx
> +                                      />
This should be a TextInput and not a TextAreaField

2024-01-11 17:31 UTC, patrickseguraoddball commented on src/views/ModelPlan/TaskList/GeneralCharacteristics/TargetsAndOptions/index.tsx
> +                          </Label>
This label should not be bold

2024-01-11 17:31 UTC, patrickseguraoddball commented on src/views/ModelPlan/TaskList/GeneralCharacteristics/TargetsAndOptions/index.tsx
> +                          </Label>
This label should not be bold

2024-01-11 17:40 UTC, garyjzhao commented
Hi @StevenWadeOddball, yes, this is only the FE changes. It may have tagged BE because it had branched off work @OddTomBrooks did on the BE. Please disregard BE review in this ticket

2024-01-11 17:50 UTC, StevenWadeOddball commented
Thanks @garyjzhao , I'll hold off on review of this then. To note, if you merge this to the feature branch before the BE branch, this will show incorrect git history (because we use squash and merge). I"ll take myself off as a reviewer

2024-01-11 18:04 UTC, garyjzhao commented
@StevenWadeOddball thanks for the info. I put on a `do not merge` tag until the BE is ready to go

2024-01-18 16:52 UTC, patrickseguraoddball commented
Also the csv label header isnt rendering correctly, nor the data being populated.  i had populated some states here

![Screenshot 2024-01-18 at 10 51 45 AM](https://github.com/CMSgov/mint-app/assets/95709965/20b5874a-2bc7-486c-8a71-5e26b06930f0)

2024-01-19 19:31 UTC, patrickseguraoddball requested changes

2024-01-19 19:31 UTC, patrickseguraoddball commented on src/views/ModelPlan/ReadOnly/GeneralCharacteristics/index.tsx
> +                    </em>
You can just pass null here if there are no values selected and the component will render `No additional information specified` correctly

2024-01-19 19:31 UTC, patrickseguraoddball commented on src/i18n/en-US/modelPlan/generalCharacteristics.ts
> +  noAdditionalInformation: 'No additional information specified'
Per the other comment, this translation isn't needed

2024-01-19 20:32 UTC, patrickseguraoddball approved these changes
LG!

2024-01-19 20:32 UTC, merged