EASI-3835: remove logstash/opensearch from local deployment
CMSgov/mint-app pull request #922
Opened 2024-01-27 04:02 UTC by Jdwoodson

# EASI-3835

## Changes and Description

- remove logstash/opensearch from local deployment via docker compose

## How to test this change

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2024-01-29 17:00 UTC, ClayBenson94 commented
@Jdwoodson Converting this to draft. I think we should have the backend code removed on this as well. I'll work with the BE folks to get this done in this PR! (That way we can tag the commit in `main` before this goes in as the final "pre removal" commit)

2024-02-07 13:53 UTC, ClayBenson94 requested changes
Also looks like the `pkg/querybuilderfilters` tests are failing due to missing references to auto-generated types no longer being present.

I think we should just delete the `querybuilderfactories`, `querybuilderfilters`, and `pkg/oddsearch` packages along with the other code here, since it all ties in with OpenSearch.

2024-02-07 13:53 UTC, ClayBenson94 commented on .spelling
> -Opensearch
Removing these lines is causing linters to fail due to these terms existing in ADRs. These shouldn't be removed for that reason!

2024-02-07 14:55 UTC, OddTomBrooks commented
Since we have review on this I’m promoting this from draft and addressing feedback.

2024-02-08 13:25 UTC, ClayBenson94 approved these changes
Changes look good! @Jdwoodson, since you're the author, are you good to merge this and deploy it out?

2024-02-08 14:34 UTC, merged