[EASI-3944] Notifications - On Discussion Replied Notification
CMSgov/mint-app pull request #990
Opened 2024-03-06 16:42 UTC by OddTomBrooks

# EASI-3944

## Changes and Description

- TODO

## How to test this change

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

2024-03-06 17:40 UTC, StevenWadeOddball reviewed
Thanks @OddTomBrooks, this looks like you are on the right track!

I added some more notes as you continue to finalize the implementation.

The other thing not called out is just updating postman as well.

2024-03-06 17:40 UTC, StevenWadeOddball commented on pkg/notifications/new_discussion_replied_meta.go
> +	activity := models.NewNewDiscussionRepliedActivity(actorID, discussionID, replyID, discussionContent.RawContent.String())
I think this should actually be the discussion reply content, not the discussion content.

2024-03-06 17:40 UTC, StevenWadeOddball commented on pkg/notifications/new_discussion_replied_meta.go
> +
This method should also be responsible for creating the notification as well. I think it should go to the created user of the discussion.

2024-03-06 17:40 UTC, StevenWadeOddball commented on pkg/notifications/new_discussion_replied_meta_test.go
> +func (suite *NotificationsSuite) TestActivityNewDiscussionRepliedCreate() {
This is a good start, you probably could do without any tags in this test, the other activity type really deals with the tagged notification. I'd expect assertions that
1. The user that made the discussion gets a notification for the reply, and then assert the content matches as expected.

2024-03-06 17:40 UTC, StevenWadeOddball commented on pkg/models/new_discussion_replied_meta.go
> +type NewDiscussionRepliedActivityMeta struct {
This looks pretty good! I'd do a final pass looking at [Figma](https://www.figma.com/file/8MfXzXzmKWv8vBjTasUIkD/MINT---Notifications?type=design&node-id=3472-13198&mode=design&t=q13knZsma5QK1gdV-0) and include any other fields that might be needed. At A glance, I think we might need model_plan_ID to be stored, as well as a resolver to modelPlan.

I added this onto Gary's [PR](https://github.com/CMSgov/mint-app/pull/988) for the reply notification type, I didn't realize it was needed, but it's important for rendering.

2024-03-06 17:40 UTC, StevenWadeOddball commented on pkg/graph/resolvers/plan_discussion.go
> +		if !pref.NewDiscussionReply.SendEmail() {
This is going to make some issues, the tag emails have their own preferences, so this specific preference shouldn't block those emails. (The tag emails are based on the preference of each individual who is tagged, while is this should be based on the preference of the user who created the discussion.

2024-03-06 17:40 UTC, StevenWadeOddball commented on pkg/graph/resolvers/plan_discussion.go
> +		pref, err := UserNotificationPreferencesGetByUserID(ctx, principal.Account().ID)
I think this is getting preferences for the wrong user, it should be getting the preferences of the user who created the discussion, not the preferences of the user who made the reply. The discussion creator should get the notification

2024-03-06 17:40 UTC, StevenWadeOddball commented on pkg/graph/resolvers/plan_discussion.go
> +		}
Somewhere in this flow, the notification method needs to get called still.  `notifications.ActivityNewDiscussionRepliedCreate`

the actor should be the user who made the reply, but the notification should go to the user who created the discussion.

2024-03-14 16:56 UTC, StevenWadeOddball commented
Review is in progress still. @OddTomBrooks, can you target the feature branch here please? This shouldn't merge to main until the frontend is built out.

2024-03-14 18:23 UTC, StevenWadeOddball requested changes
Thanks @OddTomBrooks, this is almost there!

I functionally tested the change with postman. I confirmed that a notification is created as expected, and that the email respects the user preference to only send an email when it is activated.

2024-03-14 18:23 UTC, StevenWadeOddball commented on pkg/graph/resolvers/plan_discussion.go
> +		_, notificationErr := notifications.ActivityTaggedInDiscussionReplyCreate(ctx, tx, discussion.CreatedBy, discussion.ModelPlanID, discussion.ID, reply.ID, reply.Content, loaders.UserNotificationPref
This method call was updated incorrectly, `principal.Account().ID` is the actor, you switched it to `discussion.CreatedBy`. Can you please revert the change you made to this line?

2024-03-14 18:23 UTC, StevenWadeOddball commented on pkg/graph/resolvers/activity.resolvers.go
> +func (r *newDiscussionRepliedActivityMetaResolver) ModelPlanID(ctx context.Context, obj *models.NewDiscussionRepliedActivityMeta) (uuid.UUID, error) {
Can you delete this please?

2024-03-14 18:23 UTC, StevenWadeOddball commented on pkg/notifications/notifications_test.go
> +func (suite *NotificationsSuite) deserializeActivityMetadata(testActivity *models.Activity) models.ActivityMetaData {
Optional: Could you add a comment to this test function? That would be helpful if the hope is to use this in other functions where the same logic is being tested.

2024-03-14 20:57 UTC, OddTomBrooks commented
> Thanks @OddTomBrooks, this is almost there!
> 
> I functionally tested the change with postman. I confirmed that a notification is created as expected, and that the email respects the user preference to only send an email when it is activated.

Thank you for the thorough review. All of your requests are in and ready for re-review, a request has also been sent.

2024-03-14 21:14 UTC, StevenWadeOddball approved these changes
Thanks for making the changes @OddTomBrooks, this looks good to go.

2024-03-14 21:46 UTC, merged